version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"  # FastAPI
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=datapipeline
      - PYTHONPATH=/app
    depends_on:
      - minio
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build: .
    ports:
      - "8501:8501"  # Streamlit
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=datapipeline
      - PYTHONPATH=/app
    depends_on:
      - minio
    command: streamlit run app/ui/main.py --server.port 8501 --server.address 0.0.0.0

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: 